name: "Get & Cache Dependencies"
discription: "Get the dependencies (via npm) and cache them."
inputs:
  caching:
    description: "Whether to cache dependencies or not."
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node-modules
        key: deps-node-modudes-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      shell: bash
      run: npm ci
