name: "Build eco-ci results"
description: "Create Energy Results"
inputs:
  source-type:
    description: "The source of the event"
    required: false
    default: "CI"
  display-results:
    description: "Whether to print table results in pipe"
    required: false
    default: "false"
  application:
    description: "The application name"
    required: true
  namespace:
    description: "The namespace of the application."
    required: true
  owner:
    description: "The owner of the application."
    required: true
  infra:
    description: "The infra enviorment. Ex: onpremises, aws, azure, gcp"
    required: true
  region:
    description: "The region of infra enviorment."
    required: true
outputs:
  energy-results:
    description: "The created Energy Results JSON"
    value: ${{ steps.energy-results.outputs.energy-results }}
runs:
  using: "composite"
  steps:
    - name: Setup Python Measurment
      uses: green-coding-berlin/eco-ci-energy-estimation@v1
      with:
        task: get-measurement
        label: "python setup"
        send-data: false

    - name: Create Energy Results
      if: inputs.display-results == 'true'
      uses: green-coding-berlin/eco-ci-energy-estimation@v1
      with:
        task: display-results
        send-data: false
        display-graph: false
        display-badge: false

    - name: Create Energy Results
      id: energy-results
      shell: bash
      run: |
        DATE_TIME=$(date +"%Y-%m-%d %H/%M/%S");

        echo $DATE_TIME;

        IFS='| ' read -a arr <<< $ECO_CI_MEASUREMENT_TABLE_LINES;

        ENERGY_RESULTS=$( jq -n \
            --arg st ${{ inputs.source-type }} \
            --arg ap ${{ inputs.application }} \
            --arg nf ${{ inputs.infra }} \
            --arg rg ${{ inputs.region }} \
            --arg ns ${{ inputs.namespace }} \
            --arg wn ${{ inputs.owner }} \
            --arg dt \"$DATE_TIME\" \
            --arg cp ${arr[3]} \
            --arg ej ${arr[4]} \
            --arg pw ${arr[5]} \
            --arg ji ${{github.job}} \
            --arg rp ${{github.repository}} \
            --arg wf $ECO_CI_WORKFLOW_ID \
            --arg ri ${{ github.run_id }} \
            --arg mn $ECO_CI_MODEL_NAME \
            --arg cm $ECO_CI_CPU_MAKE \
            --arg ch ${{ github.sha }} \
            --arg br ${{ github.ref_name }} \
            '{sourceType: $st, application: $ap, infra: $nf, region: $rg, namespace: $ns, owner: $wn, datetime: $dt, data: {cpuAvgPercent: $cp, energyJoules: $ej, powerAvgWatts: $pw, repository: $rp, workflow: $wf, runId: $ri, jobId: $ji, commitHash: $ch, branch: $br, cpuModel: $mn, cpuMake: $cm}}' | jq tostring );

        echo $ENERGY_RESULTS;

        echo "energy-results=$ENERGY_RESULTS" >> "$GITHUB_OUTPUT";

        echo "curl -X POST \"http://api...\" -H \'Content-Type: application/json\' -d $ENERGY_RESULTS";

  # send-ci-energy-estimation:
  #   name: Send Ci Energy Estimation
  #   runs-on: ubuntu-latest
  #   needs: [test,build,deploy]
  #   steps:
  #     - name: Print JSON Energy Results
  #       run: echo "{\"sourceType\":\"CI\", \"application\":\"${{ env.app_name }}\", \"infra\":\"${{ env.infra }}\", \"region\":\"${{ env.aws_region }}\", \"namespace\":\"${{ env.namespace }}\", \"owner\":\"${{ env.value_stream }}\", \"datetime\":\"$(date +"%Y-%m-%d %T")\", \"data\":[${{ needs.test.outputs.energy-estimation }}, ${{  needs.build.outputs.energy-estimation  }}, ${{  needs.deploy.outputs.energy-estimation }}]}";
